# Generated by Django 5.1.1 on 2024-10-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
