# Generated by Django 5.1.1 on 2024-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('freezed', 'Freezed')], max_length=12, verbose_name='Status'),
        ),
    ]
