# Generated by Django 5.1.1 on 2024-10-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_public'),
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('inprogress', 'In progress'), ('finished', 'Finished'), ('freezed', 'Freezed')], max_length=12, verbose_name='Status'),
        ),
    ]
