# Generated by Django 5.1.1 on 2024-10-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_public'),
        ('tasks', '0004_alter_task_course_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='courses.course', verbose_name='Course'),
        ),
    ]
